# Generated by Django 4.2.4 on 2025-08-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('clothes', 'Clothes'), ('electronics', 'Electronics'), ('books', 'Books'), ('furniture', 'Furniture'), ('other', 'Other')], max_length=50)),
                ('is_claimed', models.BooleanField(default=False)),
            ],
        ),
    ]
